import type { Metadata } from "next";
import Image from "next/image";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import dog from "../public/assets/shiba-inu-icon.svg";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} flex flex-col antialiased`}>
        <header>
          <nav className="col flex gap-2 border-b-2 border-muted p-2">
            <Link className="flex items-center text-sm font-bold" href="/">
              <Image src={dog} width={32} height={32} alt="dog icon" /> Doge Go
              Fetch
            </Link>
            <Link
              className="font-secondary flex items-center text-center text-sm text-primary/70 hover:text-primary"
              href="/about"
            >
              About
            </Link>
            <Link
              className="flex items-center text-sm text-primary/70 hover:text-primary"
              href="/examples/introduction"
            >
              Examples
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
